package View;

import ModelCadastro.Pessoa;
import ControleCadastro.PessoaDB;
import ControleCadastro.EstadoDB;
import ControleCadastro.MunicipioDB;
import ControleCadastro.PaisDB;
import VisaoConsultasCadastro.ConsultaPessoa;
import Principal.Conexao;
import VisaoConsultasCadastro.ConsultaEstadoPessoa;
import VisaoConsultasCadastro.ConsultaMunicipio;
import VisaoConsultasCadastro.ConsultaPaises;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gelvazio
 */
public class CadPessoa extends MetodosGlobais {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        edtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edtNumero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        edtCEP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        edtCPF = new javax.swing.JTextField();
        edtTelefone = new javax.swing.JTextField();
        btnLocalizaCidade = new javax.swing.JButton();
        btnLocalizaPais = new javax.swing.JButton();
        edtCodigoCidade = new javax.swing.JTextField();
        edtCodigoPais = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLocalizaEstado = new javax.swing.JButton();
        cbEstado = new javax.swing.JComboBox();
        cbCidade = new javax.swing.JComboBox();
        cbPais = new javax.swing.JComboBox();
        edtBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RadioAtivo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RadioConsumo = new javax.swing.JRadioButton();
        Radiorevenda = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        RadioCliente = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        RadioFornecedor = new javax.swing.JRadioButton();
        RadioVendedor = new javax.swing.JRadioButton();
        RadioTransportadora = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        RadioPessoaFisica = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        RadioSimplesNacional = new javax.swing.JRadioButton();
        RadioRegimeNormal = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        edtDataCadastro = new javax.swing.JTextField();
        edtHoraCadastro = new javax.swing.JTextField();
        edtDataAlteracao = new javax.swing.JTextField();
        edtHoraAlteracao = new javax.swing.JTextField();
        cbSiglaEstado = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        edtInscricaoEstadual = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setTitle("Cadastro de Pessoa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoKeyPressed(evt);
            }
        });
        jPanel4.add(edtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, 30));

        jLabel2.setText("Nome:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 40, -1));

        edtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtNomeKeyPressed(evt);
            }
        });
        jPanel4.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 330, 30));

        jLabel4.setText("E-mail:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 40, -1));

        edtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtEmailKeyPressed(evt);
            }
        });
        jPanel4.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 330, 30));

        jLabel6.setText("Endereço:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, -1));

        jLabel8.setText("Telefone:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 60, -1));

        jLabel9.setText("Numero:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        edtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtEnderecoKeyPressed(evt);
            }
        });
        jPanel4.add(edtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 330, 30));

        jLabel10.setText("Bairro:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 50, -1));

        edtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtNumeroKeyPressed(evt);
            }
        });
        jPanel4.add(edtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 70, 30));

        jLabel13.setText("CEP:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 30, -1));

        edtCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCEPKeyPressed(evt);
            }
        });
        jPanel4.add(edtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 130, 30));

        jLabel14.setText("CPF /CNPJ:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        edtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCPFKeyPressed(evt);
            }
        });
        jPanel4.add(edtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 140, 30));

        edtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtTelefoneKeyPressed(evt);
            }
        });
        jPanel4.add(edtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 160, 30));

        btnLocalizaCidade.setText("...");
        btnLocalizaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizaCidadeActionPerformed(evt);
            }
        });
        btnLocalizaCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLocalizaCidadeKeyPressed(evt);
            }
        });
        jPanel4.add(btnLocalizaCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 30, 30));

        btnLocalizaPais.setText("...");
        btnLocalizaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizaPaisActionPerformed(evt);
            }
        });
        btnLocalizaPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLocalizaPaisKeyPressed(evt);
            }
        });
        jPanel4.add(btnLocalizaPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 30, 30));

        edtCodigoCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoCidadeKeyPressed(evt);
            }
        });
        jPanel4.add(edtCodigoCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 55, 30));
        edtCodigoCidade.getAccessibleContext().setAccessibleName("");

        edtCodigoPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoPaisKeyPressed(evt);
            }
        });
        jPanel4.add(edtCodigoPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 55, 30));
        edtCodigoPais.getAccessibleContext().setAccessibleName("");

        jLabel3.setText("Cód.Cidade:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 70, -1));

        jLabel5.setText("Cód País:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 60, -1));

        jLabel7.setText("Cód.Estado:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 70, -1));

        btnLocalizaEstado.setText("...");
        btnLocalizaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizaEstadoActionPerformed(evt);
            }
        });
        btnLocalizaEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLocalizaEstadoKeyPressed(evt);
            }
        });
        jPanel4.add(btnLocalizaEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 30, 30));

        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });
        jPanel4.add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 270, 30));

        cbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCidadeActionPerformed(evt);
            }
        });
        jPanel4.add(cbCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 270, 30));

        cbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisActionPerformed(evt);
            }
        });
        jPanel4.add(cbPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 270, 30));

        edtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtBairroKeyPressed(evt);
            }
        });
        jPanel4.add(edtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 190, 30));

        jLabel11.setText("Código:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        RadioAtivo.setText("Ativo");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Tipo de Consumo:");

        RadioConsumo.setText("Consumo");
        RadioConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioConsumoActionPerformed(evt);
            }
        });

        Radiorevenda.setText("Revenda");
        Radiorevenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadiorevendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Radiorevenda)
                                        .addComponent(RadioConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadioConsumo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Radiorevenda)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        RadioCliente.setText("Cliente");

        jLabel12.setText("Tipo de Cadastro:");

        RadioFornecedor.setText("Fornecedor");

        RadioVendedor.setText("Vendedor");

        RadioTransportadora.setText("Transportadora");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RadioVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RadioCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RadioFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RadioTransportadora, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioVendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioTransportadora)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        RadioPessoaFisica.setText("Sem Regime(Pessoa Física)");
        RadioPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioPessoaFisicaActionPerformed(evt);
            }
        });

        jLabel15.setText("Regime de Tributação:");

        RadioSimplesNacional.setText("Simples Nacional");
        RadioSimplesNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioSimplesNacionalActionPerformed(evt);
            }
        });

        RadioRegimeNormal.setText("Regime Normal");
        RadioRegimeNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioRegimeNormalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(RadioPessoaFisica, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                                .addComponent(RadioSimplesNacional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(RadioRegimeNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel15))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioPessoaFisica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioSimplesNacional)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RadioRegimeNormal)
                                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setText("Data Cadastro:");

        jLabel19.setText("Hora Cadastro:");

        jLabel20.setText("Data Alteração:");

        jLabel21.setText("Hora Alteração:");

        edtDataCadastro.setEditable(false);
        edtDataCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtDataCadastroKeyPressed(evt);
            }
        });

        edtHoraCadastro.setEditable(false);
        edtHoraCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtHoraCadastroKeyPressed(evt);
            }
        });

        edtDataAlteracao.setEditable(false);
        edtDataAlteracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtDataAlteracaoKeyPressed(evt);
            }
        });

        edtHoraAlteracao.setEditable(false);
        edtHoraAlteracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtHoraAlteracaoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(edtDataCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(edtHoraCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(4, 4, 4)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(edtHoraAlteracao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(edtDataAlteracao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(edtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel19)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(edtHoraCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(edtDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel20))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(edtHoraAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel21))
                                                .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(RadioAtivo)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(RadioAtivo)
                                .addGap(7, 7, 7)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 220, -1));

        cbSiglaEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        cbSiglaEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbSiglaEstadoKeyPressed(evt);
            }
        });
        jPanel4.add(cbSiglaEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 30));

        jLabel17.setText("Insc.Estadual:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        edtInscricaoEstadual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtInscricaoEstadualKeyPressed(evt);
            }
        });
        jPanel4.add(edtInscricaoEstadual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 100, 30));

        jTabbedPane1.addTab("Cadastro", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 680, 530));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Cadastro de Pessoas");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Faturamento/Knob Valid Green.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        btnGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGravarKeyPressed(evt);
            }
        });
        getContentPane().add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 120, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Faturamento/Knob Cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 120, 40));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Faturamento/Knob Remove Red.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        btnExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExcluirKeyPressed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 120, 40));

        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Faturamento/Knob Search.png"))); // NOI18N
        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        btnConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConsultaKeyPressed(evt);
            }
        });
        getContentPane().add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 120, 40));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Faturamento/Knob Red.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 120, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 820, 20));

        pack();
    }// </editor-fold>                        

    private void btnLocalizaCidadeActionPerformed(java.awt.event.ActionEvent evt) {
        ConsultaMunicipio formulario = new ConsultaMunicipio(edtCodigoCidade, cbSiglaEstado);
        JInternalFrame j = new JInternalFrame();
        j.getDesktopPane().add(formulario);
        formulario.setVisible(true);
    }

    private void btnLocalizaPaisActionPerformed(java.awt.event.ActionEvent evt) {
        ConsultaPaises form = new ConsultaPaises(edtCodigoPais);
        JInternalFrame j = new JInternalFrame();
        j.getDesktopPane().add(form);
        form.setVisible(true);
    }

    private void edtCodigoKeyPressed(java.awt.event.KeyEvent evt) {

        String auxTexto = edtCodigo.getText();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (auxTexto.equals("")) {
                ValidaCodigoGenerator();
                //Habilitação dos campos
                habilitaCampos(true);

                //Combobox Estado
                cbEstado.setModel(estadodb.getComboboxPessoaEstado());
                ComboBoxEstado();
                //Carrega as siglas dos estados tambem
                cbSiglaEstado.setModel(estadodb.getComboEstado());

                //Combobox Cidade
                cbCidade.setModel(cidadedb.getComboCidade());
                ComboBoxCidade();

                //Combobox Pais
                cbPais.setModel(paisdb.getComboPais());
                ComboBoxPais();
                AlteraParaDataHoraAtual();
            } else {
                ValidaCampoCodigoNaoNulo();
            }
        }
    }

    private void edtCPFKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            edtNome.grabFocus();
        }
    }

    private void edtNomeKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            edtEndereco.grabFocus();
        }
    }

    private void edtEnderecoKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            edtNumero.grabFocus();
        }
    }

    private void edtNumeroKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cbSiglaEstado.grabFocus();
        }
    }

    private void edtCodigoCidadeKeyPressed(java.awt.event.KeyEvent evt) {
        String auxTexto = edtCodigoCidade.getText();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (auxTexto.equals("")) {
                JOptionPane.showMessageDialog(null, "Código da Cidade nulo!");
                edtCodigoCidade.requestFocus();
            } else {
                ValidaCampoCodigoCidadeNaoNulo();
            }
        }
    }

    private void edtCodigoPaisKeyPressed(java.awt.event.KeyEvent evt) {

        String auxTexto = edtCodigoPais.getText();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (auxTexto.equals("")) {
                JOptionPane.showMessageDialog(null, "Código do País nulo!");
                edtCodigoPais.requestFocus();
            } else {
                ValidaCampoCodigoPaisNaoNulo();
            }
        }
    }

    private void btnLocalizaPaisKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            edtTelefone.grabFocus();
        }
    }

    private void edtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            edtCEP.grabFocus();
        }
    }

    private void edtCEPKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            edtEmail.grabFocus();
        }
    }

    private void edtEmailKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnGravar.grabFocus();
        }
    }

    private void btnLocalizaEstadoActionPerformed(java.awt.event.ActionEvent evt) {
        ConsultaEstadoPessoa formulario = new ConsultaEstadoPessoa(cbSiglaEstado, cbEstado);
        JInternalFrame j = new JInternalFrame();
        j.getDesktopPane().add(formulario);
        formulario.setVisible(true);

    }

    private void btnLocalizaEstadoKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            edtCodigoCidade.grabFocus();
        }
    }

    private void btnLocalizaCidadeKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            edtCodigoPais.grabFocus();
        }
    }

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {

        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente gravar o registro?");
        if (resposta == JOptionPane.YES_OPTION) {
            try {
                gravarAlterar();
            } catch (ParseException ex) {
                Logger.getLogger(CadPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void btnGravarKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnCancelar.grabFocus();
        }
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {

        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente Cancelar a Edição?");
        if (resposta == JOptionPane.YES_OPTION) {
            habilitaCampos(false);
            LimpaTela();
        }
    }

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnExcluir.grabFocus();
        }
    }

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {

        ExcluirRegistro();
    }

    private void btnExcluirKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnConsulta.grabFocus();
        }
    }

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {
        ConsultaPessoa form = new ConsultaPessoa(edtCodigo);
        JInternalFrame j = new JInternalFrame();
        j.getDesktopPane().add(form);
        form.setVisible(true);
        edtCodigo.grabFocus();
    }

    private void btnConsultaKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSair.grabFocus();
        }
    }

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {
        //dispose();
    }

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {

        ComboBoxEstado();
    }

    private void cbCidadeActionPerformed(java.awt.event.ActionEvent evt) {

        ComboBoxCidade();
    }

    private void cbPaisActionPerformed(java.awt.event.ActionEvent evt) {

        ComboBoxPais();
    }

    private void edtBairroKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void cbSiglaEstadoKeyPressed(java.awt.event.KeyEvent evt) {

        String auxTexto = cbSiglaEstado.getSelectedItem().toString();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (auxTexto.equals("")) {
                JOptionPane.showMessageDialog(null, "Sigla do Estado nulo!");
                cbSiglaEstado.requestFocus();
            } else {
                ValidaCampoCodigoEstadoNaoNulo();
                edtCodigoCidade.setText("");
                cbCidade.setSelectedItem("");
            }
        }
    }

    private void edtInscricaoEstadualKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void edtDataCadastroKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void edtHoraCadastroKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void edtDataAlteracaoKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void edtHoraAlteracaoKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void RadioConsumoActionPerformed(java.awt.event.ActionEvent evt) {

        Radiorevenda.setSelected(false);
    }

    private void RadiorevendaActionPerformed(java.awt.event.ActionEvent evt) {

        RadioConsumo.setSelected(false);
    }

    private void RadioPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {
        RadioSimplesNacional.setSelected(false);
        RadioRegimeNormal.setSelected(false);
    }

    private void RadioSimplesNacionalActionPerformed(java.awt.event.ActionEvent evt) {
        RadioPessoaFisica.setSelected(false);
        RadioRegimeNormal.setSelected(false);
    }

    private void RadioRegimeNormalActionPerformed(java.awt.event.ActionEvent evt) {

        RadioPessoaFisica.setSelected(false);
        RadioSimplesNacional.setSelected(false);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton RadioAtivo;
    private javax.swing.JRadioButton RadioCliente;
    private javax.swing.JRadioButton RadioConsumo;
    private javax.swing.JRadioButton RadioFornecedor;
    private javax.swing.JRadioButton RadioPessoaFisica;
    private javax.swing.JRadioButton RadioRegimeNormal;
    private javax.swing.JRadioButton RadioSimplesNacional;
    private javax.swing.JRadioButton RadioTransportadora;
    private javax.swing.JRadioButton RadioVendedor;
    private javax.swing.JRadioButton Radiorevenda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLocalizaCidade;
    private javax.swing.JButton btnLocalizaEstado;
    private javax.swing.JButton btnLocalizaPais;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JComboBox cbPais;
    private javax.swing.JComboBox cbSiglaEstado;
    private javax.swing.JTextField edtBairro;
    private javax.swing.JTextField edtCEP;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtCodigoCidade;
    private javax.swing.JTextField edtCodigoPais;
    private javax.swing.JTextField edtDataAlteracao;
    private javax.swing.JTextField edtDataCadastro;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtHoraAlteracao;
    private javax.swing.JTextField edtHoraCadastro;
    private javax.swing.JTextField edtInscricaoEstadual;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtNumero;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration                   
}
